---
- hosts: ansible

  tasks:
  - name: Create Docker image
    command: docker build -t regapp:latest .
    args:
      chdir: /opt/docker

  - name: Create tag to push image to DockerHub
    command: docker tag regapp:latest davidbulke/regapp:latest

  - name: Push Docker image
    command: docker push davidbulke/regapp:latest

  - name: Create Docker container
    command: docker run -d --name regapp-server -p 8082:8080 davidbulke/regapp:latest